# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"@\n\x0b\x43hatMessage\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\r\n\x05texto\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"3\n\x0eServerResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\" \n\rEntrarRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xbe\x01\n\x0b\x43hatService\x12\x39\n\x0e\x45nviarMensagem\x12\x11.chat.ChatMessage\x1a\x14.chat.ServerResponse\x12<\n\x10ReceberMensagens\x12\x13.chat.EntrarRequest\x1a\x11.chat.ChatMessage0\x01\x12\x36\n\nChatStream\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=84
  _globals['_SERVERRESPONSE']._serialized_start=86
  _globals['_SERVERRESPONSE']._serialized_end=137
  _globals['_ENTRARREQUEST']._serialized_start=139
  _globals['_ENTRARREQUEST']._serialized_end=171
  _globals['_EMPTY']._serialized_start=173
  _globals['_EMPTY']._serialized_end=180
  _globals['_CHATSERVICE']._serialized_start=183
  _globals['_CHATSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
